language: node_js
node_js:
  - "0.8"
  - "0.10"
services:
  - couchdb
before_install:
  - sudo apt-get install python-software-properties
  - sudo apt-add-repository ppa:ubuntugis/ppa -y
  - sudo apt-get update
  - sudo apt-get install gdal-bin
  - ogr2ogr --formats
  - sudo apt-get install python-dateutil python-tz python-sqlalchemy