language: node_js
node_js:
  - "0.8"
  - "0.10"
services:
  - couchdb
before_install:
  - sudo apt-get install python-software-properties
  - sudo apt-add-repository ppa:ubuntugis/ppa -y
  - sudo apt-get update
  - sudo apt-get install gdal-bin
  - ogr2ogr --formats
before_script: curl https://raw.github.com/rclark/travis-solr/master/travis-solr.sh | SOLR_VERSION=4.4.0 SOLR_CONFS=solr/schema.xml bash